package PlayerCharacter;

public enum AdvancedCharacterClass {
    BATTLEMASTER, DUELIST, SPELLSWORD, PALADIN,
    SWASHBUCKLER, NINJA, ILLUSIONIST, INQUISITOR,
    BATTLEMAGE, SHADOWMAGE, ARCHMAGE, ORACLE,
    CLERIC, DIVINETRICKSTER, BISHOP, CARDINAL;
}
